### ISSUE TITLE
Some artifacts in old photos

### ISSUE THREAD

**Issue by EdVince** [csxmli2016/ReDegNet#2]
Thanks for your excellent work. But when I use this to enhance some of my old photos, I observe some disappointment artifacts. Do you have any plans or ideas to improve it? (first is the origin image, second is the enhanced one, this is not the only one fail case, still more)
![origin](https://user-images.githubusercontent.com/18224516/193975483-faced11c-0c35-4e15-bee0-9548b4e48200.jpeg)
![enhanced](https://user-images.githubusercontent.com/18224516/193975501-f4c2c932-dd2f-4dcc-a362-0f229ff9fb36.jpeg)

**Comment by csxmli2016** [comment]
Hi, thanks very much for your feedback. The released restoration model ('init') is mainly fine-tuned with the specific degradation from Figure 1. So it would be more suitable to handle this specific image. I also upload a general restoration model that could generate little artifacts. Please see our revised Readme. This is the updated result.
![g_F2NESRGAN](https://user-images.githubusercontent.com/26357039/193987958-c534823b-61b9-49a3-b304-a8532a05cf8e.png)
