### ISSUE TITLE
About the scale

### ISSUE THREAD

**Issue by mrgreen3325** [csxmli2016/ReDegNet#3]
Hello.
Thanks for your great work and the code sharing.
I have several questions about the paper.
1. May I know the sr results that comparing with realesrgan bsrgan are in which upscale?
2. Can I simply replace the RRDB to other sr network, e.g. edsr? 
3. I have tried the test_degradation, and it results in an image that with artifact and without a pixel downsampling, is that right?
4. Also, I notice that the real-world LQ/HQ in Train data contains around 10 images, is it need more if I want to retrain the network?
Thanks a lot.

**Comment by csxmli2016** [comment]
> Hello. Thanks for your great work and the code sharing. I have several questions about the paper.
> 
> 1. May I know the sr results that comparing with realesrgan bsrgan are in which upscale?
> 2. Can I simply replace the RRDB to other sr network, e.g. edsr?
> 3. I have tried the test_degradation, and it results in an image that with artifact and without a pixel downsampling, is that right?
> 4. Also, I notice that the real-world LQ/HQ in Train data contains around 10 images, is it need more if I want to retrain the network?
>    Thanks a lot.

1. You can refer to the output size. It is x4 SR.
2. Yes. This work is for building the training data. You can use any SR network.
3. Yes. In this version, you can regard the input is upsampled to 4 times. You can refer to the LR size in our manner (see the prepare_validation function in redeg_model.py).
4. These paired data belong to Alibaba. I am not allowed to release them. These 10 images are examples of how to prepare the LQ/HQ pairs.
