### ISSUE TITLE
real-world LQ dataset

### ISSUE THREAD

**Issue by pengzz-ops** [csxmli2016/ReDegNet#4]
Thank you for providing such excellent work. I am currently trying to reproduce your work. I wonder if you could provide me with a real-world facial dataset that you found through internet search?

**Comment by csxmli2016** [comment]
> 

Thanks for your attention. These facial dataset belongs to Alibaba DAMO academy. I am not allowed to release them. You can scrawl these types of LQ dataset from Internet and restore them using any SoTA face restoration methods.
