### ISSUE TITLE
What if training without restoration model

### ISSUE THREAD

**Issue by mst6750623** [csxmli2016/ReDegNet#5]
Thanks for your wonderful work! I'm trying to train your model in 512*512 resolution to generate degradation LQ for my HQ dataset. However, due to 512 resolution is too big for my GPU(14G RAM), I can only set batch size 2 and remove the F2N restoration model, just train redegnet, synE and synG. But I can't get a proper degradation result at this setting. I wonder if training with restoration model is necessary or have you made this ablation experiment?
Thanks and watching for your answer!

**Comment by joe-zxh** [comment]
我也有类似的疑惑，似乎F2N 和 ReDegNet的训练是独立的，不知道为什么要放在一起训练

希望作者大佬可以解答一下，谢谢
